"""Convert a trained QLearningAgent's Q-table to a JS-loadable file.

The exported file assigns `window.QTABLE = { ... }`. The inner object is
deliberately also valid JSON, so test code can json.loads() the payload
to roundtrip-check it.

Format:
    {
        "numStates": <int>,
        "states": {
            "<board as 9 comma-separated ints>": [<9 floats or null>, ...],
            ...
        }
    }

Where:
    * Board ints are in {-1, 0, +1}, side-to-move canonical (agent's pieces
      are +1, opponent's are -1, empty is 0). This is the EXACT same
      representation the Python Q-table uses internally.
    * Each state maps to a 9-element array of Q-values, one per cell.
    * Cells that are ILLEGAL (occupied by a piece) are stored as null
      (= NaN in the original Q-array). All other entries are finite
      Python floats.

Why a JS file (not raw JSON)?  The user requested a "JS file" so the HTML
can load it via a plain <script src="qtable.js"></script> tag without a
fetch() roundtrip. The JS object literal form is equivalent to JSON for
our purposes — the only structural difference is the `window.QTABLE =`
wrapper, which we strip in tests.

Public API:
    qtable_to_js_dict(agent) -> dict
    write_qtable_js(agent, path, source_path=None, seed=None) -> None
"""
from __future__ import annotations

import datetime
import json
from pathlib import Path

import numpy as np

from rl_ttt.agent import QLearningAgent


def qtable_to_js_dict(agent: QLearningAgent) -> dict:
    """Return a JSON-serializable dict representation of the agent's Q-table.

    NaN values (illegal cells in the Q-array) become None, which json.dumps
    renders as `null` and JS reads back as `null`. All other Q-values are
    coerced to native Python floats so json.dumps does not raise on
    numpy.float64.
    """
    states: dict[str, list[float | None]] = {}
    for board, q_array in agent._q_table.items():
        key = ",".join(str(int(v)) for v in board)
        row: list[float | None] = []
        for v in q_array:
            f = float(v)
            row.append(None if np.isnan(f) else f)
        states[key] = row
    return {
        "numStates": agent.num_states,
        "states": states,
    }


def write_qtable_js(
    agent: QLearningAgent,
    path: str | Path,
    source_path: str | None = None,
    seed: int | None = None,
) -> None:
    """Write the agent's Q-table as a JS-loadable file at `path`.

    The file format is:
        // <provenance header>
        window.QTABLE = <JSON object>;

    `source_path` and `seed` are recorded in the header for traceability;
    they are not used at load time.
    """
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)

    payload = qtable_to_js_dict(agent)
    # json.dumps with no indentation produces a compact, single-line object
    # literal that is also valid JS object syntax (when keys are quoted, as
    # json.dumps guarantees).
    inner = json.dumps(payload, separators=(",", ":"))

    ts = datetime.datetime.now().isoformat(timespec="seconds")
    header_lines = [
        f"// Generated by rl_ttt.export on {ts}.",
        f"// Source Q-table: {agent.num_states} states.",
    ]
    if source_path is not None:
        header_lines.append(f"// Source path: {source_path}")
    if seed is not None:
        header_lines.append(f"// Source seed: {seed}")
    header = "\n".join(header_lines) + "\n"

    path.write_text(header + f"window.QTABLE = {inner};\n")
