CC = gcc
CXX = g++
CPPFLAGS = -g -O3 -Wall -march=native -pthread
CXXFLAGS = -std=c++17

.PHONY: all
all:

.PHONY: clean
clean:
	rm -f uniq-ptr shared-ptr sort minmax sort-range minmax-penalty sort-nth
