apiVersion: v1
kind: Pod
metadata:
  name: kubia-manual
spec:
  containers:
  - image: cyb70289/kubia
    name: kubia
    ports:
    - containerPort: 8080
      protocol: TCP
  nodeSelector:
    kubernetes.io/hostname: k8s-master1
